// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';

export function Greet(arg1:string):Promise<string>;

export function WriteToInflux(arg1:client.Client,arg2:string,arg3:Array<string>):Promise<void>;
